window.StreetzCommunityData = Object.freeze([
  Object.freeze({
    id: "customer-001",
    image: "images/community/customer-001.webp",
    imageLarge: "images/community/customer-001-large.webp",
    alt: "Person sitting on a black and blue sport motorcycle making a peace sign",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Official Gear / Yamaha R1",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-002",
    image: "images/community/customer-002.webp",
    imageLarge: "images/community/customer-002-large.webp",
    alt: "Person wearing a black Streetz Aint Safe t-shirt with a blue circular logo",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz Aint Safe Logo Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-003",
    image: "images/community/customer-003.webp",
    imageLarge: "images/community/customer-003-large.webp",
    alt: "A smiling girl and a man wearing a black Atlanta Braves cap standing under a red tent, with the girl holding a packaged Streetz X Safe t-shirt",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Packaged Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-004",
    image: "images/community/customer-004.webp",
    imageLarge: "images/community/customer-004-large.webp",
    alt: "Three men standing under a red tent displaying Streetz X Safe merchandise",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Official Ride Gear",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-005",
    image: "images/community/customer-005.webp",
    imageLarge: "images/community/customer-005-large.webp",
    alt: "Person standing next to a blue tent holding a packaged Streetz X Safe t-shirt",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Packaged Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-006",
    image: "images/community/customer-006.webp",
    imageLarge: "images/community/customer-006-large.webp",
    alt: "Man wearing black Streetz X Safe logo t-shirt and sunglasses standing under event tent with hanging hoodie",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Logo Tee / Hoodie",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-007",
    image: "images/community/customer-007.webp",
    imageLarge: "images/community/customer-007-large.webp",
    alt: "Two men under event tent showcasing black Streetz X Safe hoodie and t-shirt with thumbs up",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Hoodie & Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-008",
    image: "images/community/customer-008.webp",
    imageLarge: "images/community/customer-008-large.webp",
    alt: "Two men standing together outdoors holding up and representing the Streetz X Safe t-shirt",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-009",
    image: "images/community/customer-009.webp",
    imageLarge: "images/community/customer-009-large.webp",
    alt: "Two supporters displaying Streetz X Safe hoodie and logo t-shirt with hand signs and thumbs up",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Hoodie & Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-010",
    image: "images/community/customer-010.webp",
    imageLarge: "images/community/customer-010-large.webp",
    alt: "Rider in Streetz X Safe gear leaning over custom carbon fiber and purple Yamaha sport motorcycle",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Official Ride Gear / Yamaha Superbike",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-011",
    image: "images/community/customer-011.webp",
    imageLarge: "images/community/customer-011-large.webp",
    alt: "Two custom Yamaha sport motorcycles side-by-side with purple, carbon fiber, and neon yellow details",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Official Ride Gear / Yamaha Superbikes",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-012",
    image: "images/community/customer-012.webp",
    imageLarge: "images/community/customer-012-large.webp",
    alt: "Two men doing a handclasp at the event while holding packaged Streetz X Safe merchandise",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Packaged Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-013",
    image: "images/community/customer-013.webp",
    imageLarge: "images/community/customer-013-large.webp",
    alt: "Woman and man standing together under event tent displaying packaged Streetz X Safe t-shirt",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Packaged Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-014",
    image: "images/community/customer-014.webp",
    imageLarge: "images/community/customer-014-large.webp",
    alt: "Woman sitting on custom purple and carbon fiber Yamaha sport motorcycle making peace signs",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Official Ride Gear / Yamaha Superbike",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-015",
    image: "images/community/customer-015.webp",
    imageLarge: "images/community/customer-015-large.webp",
    alt: "Three men representing at the Streetz X Safe event booth showcasing packaged gear",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Packaged Gear",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-016",
    image: "images/community/customer-016.webp",
    imageLarge: "images/community/customer-016-large.webp",
    alt: "Back view of person wearing black Streetz Aint Safe circular logo graphic t-shirt",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz Aint Safe Graphic Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-017",
    image: "images/community/customer-017.webp",
    imageLarge: "images/community/customer-017-large.webp",
    alt: "Man holding packaged Streetz X Safe merchandise at the event booth",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Packaged Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-018",
    image: "images/community/customer-018.webp",
    imageLarge: "images/community/customer-018-large.webp",
    alt: "Rider in checkered jersey holding packaged Streetz X Safe merchandise in front of face",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Packaged Tee",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-019",
    image: "images/community/customer-019.webp",
    imageLarge: "images/community/customer-019-large.webp",
    alt: "Person wearing black Streetz X Safe hoodie and riding boots throwing hand signs",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Hoodie",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-020",
    image: "images/community/customer-020.webp",
    imageLarge: "images/community/customer-020-large.webp",
    alt: "Full body shot of rider wearing black Streetz X Safe hoodie and motorcycle boots",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Hoodie",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-021",
    image: "images/community/customer-021.webp",
    imageLarge: "images/community/customer-021-large.webp",
    alt: "Back view of person wearing black Streetz Aint Safe circular logo hoodie",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz Aint Safe Hoodie",
    instagram: "",
    caption: "",
    featured: true
  }),
  Object.freeze({
    id: "customer-022",
    image: "images/community/customer-022.webp",
    imageLarge: "images/community/customer-022-large.webp",
    alt: "Two men standing together at the event booth wearing Streetz X Safe hoodie and t-shirt",
    name: "",
    location: "Cycle Gear Atlanta",
    product: "Streetz X Safe Hoodie & Tee",
    instagram: "",
    caption: "",
    featured: true
  })
]);
